### ISSUE TITLE
How can I use custom fonts?

### ISSUE THREAD

**Issue by sergio9929** [sidebase/nuxt-pdf#11]
### Ask your question

Hello,

I'm trying to use [Satoshi](https://www.fontshare.com/fonts/satoshi), a custom font from FontShare, and I'm not being able to get it working. I've tried downloading the font and adding this to the html options in `exportToPDF()`:
```js
fontFaces: [{
    family: 'satoshi',
    weight: 'normal',
    src: [{
        url: '/GHM6WVH6MILNYOOCXHXB5GTSGNTMGXZR.woff',
        format: 'woff',
    }]
}],
```

I've googled about it and everyone is adding the font using `jsPDF.addFont()` and `setFont()` and I don't know how to access to those things outside of `exportToPDF().then()`.

I'm of course using the font in my css:
```css
html {
    overflow-x: hidden;
    background-color: var(--base-color);
    color: var(--primary-color);
    font-size: 16px;
    font-family: 'Satoshi', sans-serif;
    scroll-behavior: smooth;
}
```

And I also console logged `jsPDF.getFontList()`:
```js
{
    "helvetica": [
        "normal",
        "bold",
        "italic",
        "bolditalic"
    ],
    "Helvetica": [
        "",
        "Bold",
        "Oblique",
        "BoldOblique"
    ],
    "courier": [
        "normal",
        "bold",
        "italic",
        "bolditalic"
    ],
    "Courier": [
        "",
        "Bold",
        "Oblique",
        "BoldOblique"
    ],
    "times": [
        "normal",
        "bold",
        "italic",
        "bolditalic"
    ],
    "Times": [
        "Roman",
        "Bold",
        "Italic",
        "BoldItalic"
    ],
    "zapfdingbats": [
        "normal"
    ],
    "ZapfDingbats": [
        ""
    ],
    "symbol": [
        "normal"
    ],
    "Symbol": [
        ""
    ]
}
```

Help would be much appreciated 🙂
